---
- name: Create New Users
  hosts: ec2
  gather_facts: false
  tasks:
    - name: Create Users Task
      user:
        name: "{{ item.name }}"
        comment: "{{ item.comment }}"
        state: present
        password: "{{ default_user_password | password_hash('sha512') }}"
        shell: /bin/bash
        group: "{{ wheel_group }}"
        append: true
      loop:
        - { name: 'user1', comment: 'User One' }
        - { name: 'user2', comment: 'User Two' }
        - { name: 'user3', comment: 'User Three' }
        - { name: 'user4', comment: 'User Four' }
   
