---
- name:  List users
  hosts: ec2
  gather_facts: false
  tasks:
    - shell: "awk -F: '{ if(($3 >= 500)&&($3 <65534)) print $1, $3, $5 }' /etc/passwd"
      register: ps

    - debug: msg={{ ps.stdout.split('\n') }}
 
     
