---
- name: Delete users
  hosts: ec2
  gather_facts: false
  tasks:
    - name: Delete Users
      user: 
        name: "{{ item }}"
        state: absent
        remove: true
      loop:
        - user1
        - user2
        - user3
        - user4
